#!/usr/bin/env bash

#/ command: vms:list-vms: "list vms"
#/ usage: rerun vms:list-vms [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh list-vms || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

echo "Running VirtualBox VMs"
vboxmanage list runningvms

echo " "
echo "All VirtualBox VMs"
vboxmanage list vms

echo " "
echo "All Vagrant VMs"
vagrant global-status

echo " "
echo "Free Memory"
python ~/memReport.py

echo " "
echo "Disk Usage"
df -h

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

