.TH vms 1 "Wed Mar 30 14:09:54 PDT 2016" "Version 1.0.0" "RERUN User Manual" 
.SH NAME
vms \- manage local VMs
.PP
.SH SYNOPSIS
.PP
\f[CR] 
rerun [ARGS] vms: [ init-alpine | list-vms | stop-acs ] [OPTIONS]
\f[]

.SH COMMANDS
.SH vms:init-alpine \f[]

init Vagrantfile for alpine linux
.PP
\f[I]OPTIONS\f[]

.SH vms:list-vms \f[]

list vms
.PP
\f[I]OPTIONS\f[]

.SH vms:stop-acs \f[]

stop ACS VMs
.PP
\f[I]OPTIONS\f[] ; # command section done.

.SH RETURN VALUES
.PP
Successful completion: 0
.SH AUTHORS
Lindis
.SH "SEE ALSO"
rerun
.SH KEYWORDS
vms
