#!/usr/bin/env bash

#/ command: vms:init-alpine: "init Vagrantfile for alpine linux"
#/ usage: rerun vms:init-alpine [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh init-alpine || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

vagrant init maier/alpine-3.1.3-x86_64

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

