# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu Mar 12 12:15:50 PDT 2015
#
#/ usage: cliqrapp:delete  --id <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --id) rerun_option_check $# $1; ID=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set
    [ -z "$ID" ] && { echo >&2 "missing required option: --id" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export ID
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${ID:=}


