# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri Nov 13 14:35:17 PST 2015
#
#/ usage: cliqrapp:terminate-protection  --new-value <>  --id <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --new-value) rerun_option_check $# $1; NEW_VALUE=$2 ; shift ;;
            --id) rerun_option_check $# $1; ID=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set
    [ -z "$NEW_VALUE" ] && { echo >&2 "missing required option: --new-value" ; return 2 ; }
    [ -z "$ID" ] && { echo >&2 "missing required option: --id" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export NEW_VALUE
    export ID
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${NEW_VALUE:=}
: ${ID:=}


