#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: cliqrapp:terminate-protection: "Enable or Disable the terminate protection flag."
#/ usage: rerun cliqrapp:terminate-protection  --new-value <>  --id <> 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh terminate-protection || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: cliqrapp:terminate-protection. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: NEW_VALUE ID

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

test -f ~/.cliqr.env && . ~/.cliqr.env
for ID in `echo $ID|sed "s/,/ /g"`
do
    export OUT=/tmp/OUT.$$.a
    export url="https://$SERVER/job/service/preventTermination/$ID?enable=$NEW_VALUE"
    curl -sS -k -X PUT -u $API_USER:$API_PASSWORD -H "Content-Type: application/json" $url >$OUT
    cat $OUT
    echo 
    STATUSURL=`cat $OUT | jq '.resource'|sed s/\"//g`
    if [ X$STATUSURL != Xnull ]
    then
    	sleep 6
    	curl -sS -k -u $API_USER:$API_PASSWORD -H "Content-Type: application/json" $STATUSURL
	echo
    fi
done
# Done. Exit with last command exit status.
exit $?

