#!/usr/bin/env bash

#/ command: meetings:reserve-room: "reserve a room"
#/ usage: rerun meetings:reserve-room  --capacity <100> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: CAPACITY

. $RERUN_MODULE_DIR/lib/functions.sh reserve-room || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

