# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Jan 12 00:46:39 GMT 2016
#
#/ usage: cliqrapp:type-lookup  --typename <>  --cloud_tag <VMWEE> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --typename) rerun_option_check $# $1; TYPENAME=$2 ; shift ;;
            --cloud_tag) rerun_option_check $# $1; CLOUD_TAG=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$CLOUD_TAG" ] && CLOUD_TAG="$(rerun_property_get $RERUN_MODULE_DIR/options/cloud_tag DEFAULT)"
    # Check required options are set
    [ -z "$TYPENAME" ] && { echo >&2 "missing required option: --typename" ; return 2 ; }
    [ -z "$CLOUD_TAG" ] && { echo >&2 "missing required option: --cloud_tag" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export TYPENAME
    export CLOUD_TAG
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${TYPENAME:=}
: ${CLOUD_TAG:=}


