#!/usr/bin/env bash

#/ command: docker:build-jenkins-disk: "builds a jenkins disk"
#/ usage: rerun docker:build-jenkins-disk [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh build-jenkins-disk || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

docker create -v /var/jenkins_home --name jenkins-dv jenkins

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

