# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Jun 23 22:58:04 GMT 2015
#
#/ usage: cliqrapp:wait [ --id <>]  --wait <no> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --id) rerun_option_check $# $1; ID=$2 ; shift ;;
            --wait) rerun_option_check $# $1; WAIT=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$WAIT" ] && WAIT="$(rerun_property_get $RERUN_MODULE_DIR/options/wait DEFAULT)"
    # Check required options are set
    [ -z "$WAIT" ] && { echo >&2 "missing required option: --wait" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export ID
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${ID:=}
: ${WAIT:=}


