#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: cliqrapp:wait: "wait for a jobid to finish"
#/ usage: rerun cliqrapp:wait [ --id <>]  --wait <no> 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh wait || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: cliqrapp:wait. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ID WAIT

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

test -f ~/.cliqr.env && . ~/.cliqr.env

MAXWAIT=`expr $WAIT \* 60`
SEC=0   # Reset $SEC; counting of seconds will (re)start from 0(-ish).
while (( SEC < MAXWAIT ))
do
    #printf "."
    jobStatus=`curl -Ss  -k -u $API_USER:$API_PASSWORD -H "Content-Type: application/json" https://$SERVER/v1/jobs/$ID|jq -r '.status'`
    if [[ $jobStatus == 'JobRunning' ]]; then
      echo "Job successfully running: $jobStatus"
      break
    elif [[ $jobStatus != 'JobInProgress' ]]; then
      echo "Job Status failed: $jobStatus"
      exit 6
    fi

    echo "`date -u -d @${SEC} +"%T"` $SEC Job status: $jobStatus ($(date))"
    sleep 30
    SEC=`expr $SEC + 30`
done
if [ $SEC = $MAXWAIT ]
then
    echo "Job status maxwait reached: $jobStatus"
fi


# Done. Exit with last command exit status.
exit $?

