#!/usr/bin/env bash

#/ command: docker:backup-jenkins: "backup the Jenkins data and jobs"
#/ usage: rerun docker:backup-jenkins [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh backup-jenkins || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

docker cp jenkins-dv:/var/jenkins_home /tmp/jenkins-backup

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

