# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Jun 24 22:45:56 GMT 2015
#
#/ usage: cliqrapp:start [ --runname <>] [ --env_name <>] [ --ClusterName <>] [ --type <m1.medium>]  --wait <no> [ --job_list <>] [ --fmwbaseappid <295>] [ --fmwdepend <no>] [ --environment <PI>] [ --cloud <DTV_AWS_DevPI-us-west-2>] [ --subnet <subnet-02bf4e5b>] [ --vpc <vpc-82a873e7>] [ --vip_pool <updawebpi-aws_POOL>]  --cloud_tag <VMWEE> [ --version <>] [ --debug <no>] [ --fmw_job_list <>] [ --fmwinfo <>] [ --env_pairs <>] [ --appid <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --runname) rerun_option_check $# $1; RUNNAME=$2 ; shift ;;
            --env_name) rerun_option_check $# $1; ENV_NAME=$2 ; shift ;;
            --ClusterName) rerun_option_check $# $1; CLUSTERNAME=$2 ; shift ;;
            --type) rerun_option_check $# $1; TYPE=$2 ; shift ;;
            --wait) rerun_option_check $# $1; WAIT=$2 ; shift ;;
            --job_list) rerun_option_check $# $1; JOB_LIST=$2 ; shift ;;
            --fmwbaseappid) rerun_option_check $# $1; FMWBASEAPPID=$2 ; shift ;;
            --fmwdepend) rerun_option_check $# $1; FMWDEPEND=$2 ; shift ;;
            --environment) rerun_option_check $# $1; ENVIRONMENT=$2 ; shift ;;
            --cloud) rerun_option_check $# $1; CLOUD=$2 ; shift ;;
            --subnet) rerun_option_check $# $1; SUBNET=$2 ; shift ;;
            --vpc) rerun_option_check $# $1; VPC=$2 ; shift ;;
            --vip_pool) rerun_option_check $# $1; VIP_POOL=$2 ; shift ;;
            --cloud_tag) rerun_option_check $# $1; CLOUD_TAG=$2 ; shift ;;
            --version) rerun_option_check $# $1; VERSION=$2 ; shift ;;
            --debug) rerun_option_check $# $1; DEBUG=$2 ; shift ;;
            --fmw_job_list) rerun_option_check $# $1; FMW_JOB_LIST=$2 ; shift ;;
            --fmwinfo) rerun_option_check $# $1; FMWINFO=$2 ; shift ;;
            --env_pairs) rerun_option_check $# $1; ENV_PAIRS=$2 ; shift ;;
            --appid) rerun_option_check $# $1; APPID=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$TYPE" ] && TYPE="$(rerun_property_get $RERUN_MODULE_DIR/options/type DEFAULT)"
    [ -z "$WAIT" ] && WAIT="$(rerun_property_get $RERUN_MODULE_DIR/options/wait DEFAULT)"
    [ -z "$FMWBASEAPPID" ] && FMWBASEAPPID="$(rerun_property_get $RERUN_MODULE_DIR/options/fmwbaseappid DEFAULT)"
    [ -z "$FMWDEPEND" ] && FMWDEPEND="$(rerun_property_get $RERUN_MODULE_DIR/options/fmwdepend DEFAULT)"
    [ -z "$ENVIRONMENT" ] && ENVIRONMENT="$(rerun_property_get $RERUN_MODULE_DIR/options/environment DEFAULT)"
    [ -z "$CLOUD" ] && CLOUD="$(rerun_property_get $RERUN_MODULE_DIR/options/cloud DEFAULT)"
    [ -z "$SUBNET" ] && SUBNET="$(rerun_property_get $RERUN_MODULE_DIR/options/subnet DEFAULT)"
    [ -z "$VPC" ] && VPC="$(rerun_property_get $RERUN_MODULE_DIR/options/vpc DEFAULT)"
    [ -z "$VIP_POOL" ] && VIP_POOL="$(rerun_property_get $RERUN_MODULE_DIR/options/vip_pool DEFAULT)"
    [ -z "$CLOUD_TAG" ] && CLOUD_TAG="$(rerun_property_get $RERUN_MODULE_DIR/options/cloud_tag DEFAULT)"
    [ -z "$DEBUG" ] && DEBUG="$(rerun_property_get $RERUN_MODULE_DIR/options/debug DEFAULT)"
    # Check required options are set
    [ -z "$WAIT" ] && { echo >&2 "missing required option: --wait" ; return 2 ; }
    [ -z "$CLOUD_TAG" ] && { echo >&2 "missing required option: --cloud_tag" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export RUNNAME
    export ENV_NAME
    export CLUSTERNAME
    export TYPE
    export JOB_LIST
    export FMWBASEAPPID
    export FMWDEPEND
    export ENVIRONMENT
    export CLOUD
    export SUBNET
    export VPC
    export VIP_POOL
    export CLOUD_TAG
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${RUNNAME:=}
: ${ENV_NAME:=}
: ${CLUSTERNAME:=}
: ${TYPE:=}
: ${WAIT:=}
: ${JOB_LIST:=}
: ${FMWBASEAPPID:=}
: ${FMWDEPEND:=}
: ${ENVIRONMENT:=}
: ${CLOUD:=}
: ${SUBNET:=}
: ${VPC:=}
: ${VIP_POOL:=}
: ${CLOUD_TAG:=}
: ${VERSION:=}
: ${DEBUG:=}
: ${FMW_JOB_LIST:=}
: ${FMWINFO:=}
: ${ENV_PAIRS:=}
: ${APPID:=}


