# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu May 21 17:55:47 GMT 2015
#
#/ usage: cliqrapp:apps [ --appid <>] [ --shownameonly <no>] [ --version <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --appid) rerun_option_check $# $1; APPID=$2 ; shift ;;
            --shownameonly) rerun_option_check $# $1; SHOWNAMEONLY=$2 ; shift ;;
            --version) rerun_option_check $# $1; VERSION=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$SHOWNAMEONLY" ] && SHOWNAMEONLY="$(rerun_property_get $RERUN_MODULE_DIR/options/shownameonly DEFAULT)"
    # Check required options are set

    # If option variables are declared exportable, export them.
    export APPID
    export SHOWNAMEONLY
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${APPID:=}
: ${SHOWNAMEONLY:=}
: ${VERSION:=}


