#!/usr/bin/env bash

#/ command: vms:stop-acs: "stop ACS VMs"
#/ usage: rerun vms:stop-acs [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh stop-acs || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

/bin/sh /Users/Lindis/git/ansible-learning/ansible-101/environment_and_module_files/vagrant status

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

