#!/usr/bin/env bash

#/ command: docker:delete-jenkins: "delete Jenkins container"
#/ usage: rerun docker:delete-jenkins [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh delete-jenkins || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

docker rm -f jenkins

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

