#!/usr/bin/env bash

#/ command: docker:start-jenkins: "start the Jenkins container"
#/ usage: rerun docker:start-jenkins [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh start-jenkins || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

docker run -d -p 8080:8080 --volumes-from jenkins-dv --name jenkins jenkins

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

