.TH docker 1 "Tue Mar 29 19:27:34 PDT 2016" "Version 1.0.0" "RERUN User Manual" 
.SH NAME
docker \- manage docker containers
.PP
.SH SYNOPSIS
.PP
\f[CR] 
rerun [ARGS] docker: [ backupjenkins | delete-jenkins | open-jenkins | open-splunk | start-jenkins | start-splunk | stop-jenkins ] [OPTIONS]
\f[]

.SH COMMANDS
.SH docker:backupjenkins \f[]

backup jenkins jobs
.PP
\f[I]OPTIONS\f[]

.SH docker:delete-jenkins \f[]

delete Jenkins container
.PP
\f[I]OPTIONS\f[]

.SH docker:open-jenkins \f[]

open Jenkins in a web browser
.PP
\f[I]OPTIONS\f[]

.SH docker:open-splunk \f[]

open splunk in web browser
.PP
\f[I]OPTIONS\f[]

.SH docker:start-jenkins \f[]

start the Jenkins container
.PP
\f[I]OPTIONS\f[]

.SH docker:start-splunk \f[]

start the splunk container
.PP
\f[I]OPTIONS\f[]

.SH docker:stop-jenkins \f[]

stop the Jenkins container
.PP
\f[I]OPTIONS\f[] ; # command section done.

.SH RETURN VALUES
.PP
Successful completion: 0
.SH AUTHORS
Lindis
.SH "SEE ALSO"
rerun
.SH KEYWORDS
docker
