# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu Jul  2 00:36:34 GMT 2015
#
#/ usage: cliqrapp:deleteallnotrunnig [ --force <no>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --force) rerun_option_check $# $1; FORCE=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$FORCE" ] && FORCE="$(rerun_property_get $RERUN_MODULE_DIR/options/force DEFAULT)"
    # Check required options are set

    # If option variables are declared exportable, export them.

    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${FORCE:=}


