#!/usr/bin/env bash

#/ command: docker:open-docker: "Opens docker"
#/ usage: rerun docker:open-docker [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh open-docker || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

